Features/health screen UI
petcodeapp/mobile pull request #2
Opened 2021-03-01 04:36 UTC by lucaszcai

2021-03-01 06:52 UTC, YuanSamuel requested changes

2021-03-01 06:52 UTC, YuanSamuel commented on lib/screens/health/vaccine_history/add_custom_vaccine_screen.dart
> +                                ),
Maybe you could extract these to be inside StyleConstants

2021-03-01 06:52 UTC, YuanSamuel commented on lib/screens/health/vaccine_history/add_custom_vaccine_screen.dart
> +                                  color: Color(0xffbfbfbf),
Could we put this inside StyleConstants?

2021-03-01 06:52 UTC, YuanSamuel commented on lib/screens/health/vaccine_history/add_vaccine_screen.dart
> +                  Navigator.push(context, MaterialPageRoute(builder: (_) => AddCustomVaccine()));
Use auto_router

2021-03-01 06:52 UTC, YuanSamuel commented on lib/screens/health/vaccine_history/vaccine_widget.dart
> +}
Try to use Stateless if possible

2021-03-02 03:45 UTC, YuanSamuel requested changes

2021-03-02 03:45 UTC, YuanSamuel commented on lib/screens/health/health_screen.dart
> +                  onTap: () {Navigator.push(context, MaterialPageRoute(builder: (_) => RemindersScreen()));},
can you use autorouter lol

2021-03-02 03:49 UTC, lucaszcai commented on lib/screens/health/health_screen.dart
> +                  onTap: () {Navigator.push(context, MaterialPageRoute(builder: (_) => RemindersScreen()));},
I did, that code is outdated I think

2021-03-02 03:55 UTC, YuanSamuel approved these changes

2021-03-06 03:21 UTC, merged